/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Connection.Command;
import Database.Client;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author abaza
 */
public class frmAllPCs extends javax.swing.JInternalFrame {

    private MainGUI Main_Class = null;

    /**
     * Creates new form frmAllPCs
     *
     * @param Class
     */
    public frmAllPCs(MainGUI Class) {
        this.Main_Class = Class;
        try {
            initComponents();
            BusyLabel.setVisible(false);
            autoCompletionComboBox1.setEnabled(false);
            btnGet.setEnabled(false);
            Client[] DBClient = Client.queryDB(blackhat.BlackHat.ConnectDB, "WHERE " + Client.FLD_STATUS + "=" + 0);
            if (DBClient != null) {
                DefaultComboBoxModel Model = new DefaultComboBoxModel();
                for (Client client : DBClient) {
                    Model.addElement(client.getPc_name());
                }
                autoCompletionComboBox1.setModel(Model);
                autoCompletionComboBox1.setEnabled(true);
                btnGet.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, GetText("msgNoComputerOfflineNow"), GetText("tabInformation"), JOptionPane.INFORMATION_MESSAGE);
                autoCompletionComboBox1.setEnabled(false);
                btnGet.setEnabled(false);
            }
        } catch (SQLException ex) {
        }

    }

    private String GetText(String KEY) {
        return blackhat.BlackHat.local.getString(KEY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPC = new javax.swing.JPanel();
        blackHat_PC_Units1 = new BlackHatSwitchButton.BlackHat_PC_Units();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BusyLabel = new org.jdesktop.swingx.JXBusyLabel();
        jPanel2 = new javax.swing.JPanel();
        autoCompletionComboBox1 = new com.jidesoft.swing.AutoCompletionComboBox();
        btnGet = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        panelPC.setBackground(new java.awt.Color(0, 0, 0));

        blackHat_PC_Units1.setBackground(new java.awt.Color(0, 0, 0));
        blackHat_PC_Units1.setForeground(new java.awt.Color(0, 0, 0));
        blackHat_PC_Units1.setIP_Address("255.255.255.255");
        blackHat_PC_Units1.setMAC_Address("00:00:00:00");
        blackHat_PC_Units1.setPC_Name("BlackHat Computer");

        jButton2.setText(GetText("btnDelete"));

        jButton3.setText(GetText("btnChangeConfig"));

        jButton4.setText(GetText("btnUnderControl"));

        BusyLabel.setBackground(new java.awt.Color(0, 0, 0));
        BusyLabel.setBusy(true);
        BusyLabel.setForeground(new java.awt.Color(255, 0, 0));
        BusyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BusyLabel.setText("Please Wait");
        BusyLabel.setDelay(200);
        BusyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panelPCLayout = new javax.swing.GroupLayout(panelPC);
        panelPC.setLayout(panelPCLayout);
        panelPCLayout.setHorizontalGroup(
            panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPCLayout.createSequentialGroup()
                .addGroup(panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blackHat_PC_Units1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BusyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelPCLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3, jButton4});

        panelPCLayout.setVerticalGroup(
            panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPCLayout.createSequentialGroup()
                .addComponent(blackHat_PC_Units1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BusyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelPCLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3, jButton4});

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btnGet.setText(GetText("btnGetPCInformation"));
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autoCompletionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGet, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoCompletionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGet))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        try {
            String PC_Name = autoCompletionComboBox1.getSelectedItem().toString();
            String Quiry = "WHERE " + Client.FLD_PC_NAME + "='" + PC_Name + "'";
            Client PC = Client.queryFirstRow(blackhat.BlackHat.ConnectDB, Quiry);
            if (PC != null) {
                BusyLabel.setVisible(true);
                BusyLabel.setBusy(true);
                blackHat_PC_Units1.setPC_Name(PC.getPc_name().toString());
                blackHat_PC_Units1.setIP_Address(PC.getPc_ip_address().toString());
                blackHat_PC_Units1.setMAC_Address(PC.getMac().toString().replace("-", ":"));
                blackHat_PC_Units1.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        if (blackHat_PC_Units1.isRun()) {
                            try {
                                try {
                                    byte[] macBytes = getMacBytes(blackHat_PC_Units1.getMacAddress());
                                    byte[] bytes = new byte[6 + 16 * macBytes.length];
                                    for (int i = 0; i < 6; i++) {
                                        bytes[i] = (byte) 0xff;
                                    }
                                    for (int i = 6; i < bytes.length; i += macBytes.length) {
                                        System.arraycopy(macBytes, 0, bytes, i, macBytes.length);
                                    }

                                    InetAddress address = InetAddress.getByName(blackHat_PC_Units1.getIP_Address());
                                    DatagramPacket packet = new DatagramPacket(bytes, bytes.length, address, 9);
                                    try (DatagramSocket socket = new DatagramSocket()) {
                                        socket.send(packet);
                                    }

                                    BusyLabel.setText("Wake-on-LAN packet sent.");
                                } catch (IllegalArgumentException | IOException e) {
                                    BusyLabel.setText("Failed to send Wake-on-LAN packet: + e");
                                }
                                Thread.sleep(10000);
                                Main_Class.ConnectionLocal();
                                Main_Class.Scaning();
                                Main_Class.StartMotion();
                                Thread.sleep(1500);
                            } catch (InterruptedException ex) {
                            }
                        } else {
                            Main_Class.Connect(Command.SHUTDOWN);
                        }
                        BusyLabel.setVisible(false);
                        BusyLabel.setBusy(false);
                    }
                });
                blackHat_PC_Units1.updateUI();
                pack();
            } else {
                JOptionPane.showMessageDialog(this, GetText("msgThisComputerNotInYourNetwork"), GetText("lblErrorLabelMessage"), JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), GetText("lblErrorLabelMessage"), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGetActionPerformed

    private byte[] getMacBytes(String macStr) throws IllegalArgumentException {
        byte[] bytes = new byte[6];
        String[] hex = macStr.split("(\\:|\\-)");
        if (hex.length != 6) {
            JOptionPane.showMessageDialog(this, GetText("msgMACInvalid"), GetText("lblErrorLabelMessage"), JOptionPane.ERROR_MESSAGE);
        }
        try {
            for (int i = 0; i < 6; i++) {
                bytes[i] = (byte) Integer.parseInt(hex[i], 16);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, GetText("msgInvildHexMAC"), GetText("lblErrorLabelMessage"), JOptionPane.ERROR_MESSAGE);
        }
        return bytes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXBusyLabel BusyLabel;
    private com.jidesoft.swing.AutoCompletionComboBox autoCompletionComboBox1;
    private BlackHatSwitchButton.BlackHat_PC_Units blackHat_PC_Units1;
    private javax.swing.JButton btnGet;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPC;
    // End of variables declaration//GEN-END:variables
}
